import Link from "next/link";
import { Stars02 as Sparkles, MessageChatCircle as Quote } from "@untitledui/icons";
import { listJobs, listCandidatesForJob } from "@/lib/db/store";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty";

export const dynamic = "force-dynamic";

export default async function InsightsPage() {
  const jobs = await listJobs();
  const candidates = (
    await Promise.all(
      jobs.map(async (j) => {
        const cands = await listCandidatesForJob(j.id);
        return cands
          .filter((c) => c.insights && c.rank && c.rank <= 5)
          .map((c) => ({ job: j, candidate: c }));
      }),
    )
  ).flat();

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <PageHeader
        title="Explainability"
        description="Top-5 candidate justifications across every job — generated by the Insights agent (Delta-Based RAG)."
      />
      {candidates.length === 0 ? (
        <Card>
          <CardBody>
            <EmptyState
              icon={<Sparkles className="h-5 w-5" />}
              title="Run your first job"
              description="Insights are generated once each candidate is scored."
            />
          </CardBody>
        </Card>
      ) : (
        <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
          {candidates.map(({ job, candidate }) => {
            const name = job.blindMode
              ? `Candidate ${candidate.rank}`
              : candidate.cv?.name ?? candidate.filename;
            return (
              <Card key={candidate.id}>
                <CardHeader>
                  <CardTitle icon={<Quote className="h-3.5 w-3.5" />}>
                    {name}
                  </CardTitle>
                  <Badge tone="brand" dot>
                    Rank #{candidate.rank}
                  </Badge>
                </CardHeader>
                <CardBody className="space-y-3">
                  <p className="text-[13px] leading-relaxed text-ink-2">
                    {candidate.insights?.justification}
                  </p>
                  <div className="text-[11.5px] text-muted">
                    {job.title || job.jd.title} ·{" "}
                    <Link
                      className="font-medium text-brand-700 hover:underline"
                      href={`/jobs/${job.id}/candidates/${candidate.id}`}
                    >
                      open candidate →
                    </Link>
                  </div>
                </CardBody>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
